In [1]:

from pipelines.readers.b3_indices_segmentos_setoriais import ReaderSQLB3IndicesSegmentosSetoriais
from pipelines.readers.cvm_balanco_patrimonial import ReaderCSVCVMBalancoPatrimonial

from yfinance import download
from numpy import nan, arange, polyfit, polyval
from pandas import DataFrame, set_option, concat, DateOffset
from datetime import date
from dateutil.relativedelta import relativedelta

In [2]:
reader_b3_segmentos_setoriais = ReaderSQLB3IndicesSegmentosSetoriais()
df_b3_segmentos_setoriais = reader_b3_segmentos_setoriais.read(indice="IBEP")

print(df_b3_segmentos_setoriais.shape)
df_b3_segmentos_setoriais.tail(3)

(71, 7)

,Indice,Data Referencia,Código,Ação,Tipo,Qtde. Teórica,Part. (%)
68,IBEP,2026-07-13,VIVT3,TELEF BRASIL,ON,707125712,1.181
69,IBEP,2026-07-13,WEGE3,WEG,ON NM,1485954732,3.228
70,IBEP,2026-07-13,YDUQ3,YDUQS PART,ON NM,261365845,0.110

In [3]:
tickers = list(df_b3_segmentos_setoriais["Código"]) + ["^BVSP"]

In [ ]:

reader_csv_balanco_patrimonial = ReaderCSVCVMBalancoPatrimonial()

data = {}

benchmark = download("^BVSP", period="10y", interval="1d", progress=False, auto_adjust=False).droplevel(1, axis=1)[["Adj Close"]].pct_change()

for codigo in tickers:
    
    # Balanco Patrimonial
    try:
        ativo_total = reader_csv_balanco_patrimonial.read(ticker=codigo, tipo_arquivo="BPA_ind", cd_conta="1").astype(int).pct_change().iloc[:, 1].iloc[-1]
    except Exception:
        ativo_total = nan
    try:
        resultado_bruto = reader_csv_balanco_patrimonial.read(ticker=codigo, tipo_arquivo="DRE_ind", cd_conta="3.03").astype(int).pct_change().iloc[:, 1].iloc[-1]
    except Exception:
        resultado_bruto = nan    
    try:
        receita_de_vendas = reader_csv_balanco_patrimonial.read(ticker=codigo, tipo_arquivo="DRE_ind", cd_conta="3.01").astype(int).pct_change().iloc[:, 1].iloc[-1]
    except Exception:
        receita_de_vendas = nan

    try:
        serie_precos = download(codigo + ".SA" if codigo != "^BVSP" else codigo, period="10y", interval="1d", progress=False, auto_adjust=False).droplevel(1, axis=1)
    except Exception:
        
        drawdown_atual = nan
        residuo_reg_lin = nan

        continue
    
    # Drawdown
    preco_maximo = serie_precos['Adj Close'].max()
    preco_atual = serie_precos['Adj Close'].iloc[-1]
    drawdown_atual = (preco_atual - preco_maximo) / preco_maximo * 100
    
    # Regressão linear
    y = serie_precos["Adj Close"].to_numpy()
    x = arange(len(y))

    coef = polyfit(x, y, 1)      
    tendencia = polyval(coef, x)

    residuo_reg_lin = ((serie_precos["Adj Close"] - tendencia) / tendencia) * 100
    residuo_reg_lin = residuo_reg_lin.iloc[-1]
    
    # Beta
    beta = serie_precos["Adj Close"].pct_change().cov(benchmark["Adj Close"]) / benchmark["Adj Close"].var()
    
    # Retorno agrupado por mês
    serie_precos['ret'] = serie_precos["Adj Close"].pct_change()
    serie_precos['mes'] = serie_precos.index.month
    serie_precos['ano'] = serie_precos.index.year

    tabela = (
        serie_precos.groupby(['ano', 'mes'])[['ret']]
        .sum()
        .reset_index()
        .pivot(index='ano', columns='mes', values='ret')
    ) * 100
    
    data[codigo] = {
        "Ativo Total": ativo_total,
        "Resultado Bruto": resultado_bruto,
        "Receita de Vendas": receita_de_vendas,
        "Drawdown Atual": drawdown_atual,
        "Resíduo Regressão Linear": residuo_reg_lin,
        "Beta": beta,
        f"Retorno Agrupado por Mês (Média Mês:{date.today().month})": tabela[date.today().month].mean(skipna=True),
        f"Retorno Agrupado por Mês (Média Mês:{(date.today() + relativedelta(months=1)).month})": tabela[(date.today() + relativedelta(months=1)).month].mean(skipna=True),
        }

In [8]:
df_final = (
    df_b3_segmentos_setoriais.set_index("Código")
    .join(DataFrame.from_dict(data, orient="index"))
    .reset_index()
)

benchmark_row = DataFrame([{
    "Código": "^BVSP",
    "Ativo Total": nan,
    "Resultado Bruto": nan,
    "Receita de Vendas": nan,
    "Drawdown Atual": data["^BVSP"]["Drawdown Atual"],
    "Resíduo Regressão Linear": data["^BVSP"]["Resíduo Regressão Linear"],
    "Beta": data["^BVSP"]["Beta"],
    f"Retorno Agrupado por Mês (Média Mês:{date.today().month})": data["^BVSP"][f"Retorno Agrupado por Mês (Média Mês:{date.today().month})"],
    f"Retorno Agrupado por Mês (Média Mês:{(date.today() + relativedelta(months=1)).month})": data["^BVSP"][f"Retorno Agrupado por Mês (Média Mês:{(date.today() + relativedelta(months=1)).month})"]
}])

df_final = concat([df_final, benchmark_row], ignore_index=True)

set_option("display.max_rows", None)
df_final =  df_final.sort_values(by="Drawdown Atual", ascending=False)
df_final

,Código,Indice,Data Referencia,Ação,Tipo,Qtde. Teórica,Part. (%),Ativo Total,Resultado Bruto,Receita de Vendas,Drawdown Atual,Resíduo Regressão Linear,Beta,Retorno Agrupado por Mês (Média Mês:7),Retorno Agrupado por Mês (Média Mês:8)
48,PSSA3,IBEP,2026-07-13,PORTO SEGURO,ON NM,1.788254e+08,0.459,0.056534,NaN,NaN,0.000000,40.029621,0.540173,3.570144,5.421265
62,UGPA3,IBEP,2026-07-13,ULTRAPAR,ON NM,1.067870e+09,1.532,0.045903,NaN,NaN,0.000000,53.355377,1.194837,0.838524,0.262490
26,ENEV3,IBEP,2026-07-13,ENEVA,ON NM,1.913352e+09,2.462,0.041386,-0.340257,-0.268461,-0.144983,44.352006,0.751190,5.329783,4.708633
66,VBBR3,IBEP,2026-07-13,VIBRA,ON NM,1.192005e+09,1.837,0.043912,0.248137,-0.049013,-1.952617,54.981899,1.170716,4.725219,5.750551
31,GOAU4,IBEP,2026-07-13,GERDAU MET,PN N1,8.308378e+08,0.397,-0.011312,0.288102,-0.209715,-3.405863,14.708858,1.190707,8.970152,3.311804
36,ITSA4,IBEP,2026-07-13,ITAUSA,PN N1,5.970738e+09,3.952,0.028099,NaN,NaN,-4.342639,46.569249,0.969158,3.729873,2.173560
35,ISAE4,IBEP,2026-07-13,ISA ENERGIA,PN N1,4.155688e+08,0.582,0.013029,-0.013623,-0.173816,-5.139295,17.075947,0.487459,1.578116,0.623695
59,TAEE11,IBEP,2026-07-13,TAESA,UNT N2,2.185682e+08,0.426,0.035111,0.030653,0.020434,-5.657611,10.044863,0.449992,4.010960,1.427711
30,GGBR4,IBEP,2026-07-13,GERDAU,PN N1,1.258208e+09,1.352,-0.011312,0.288102,-0.209715,-6.653142,7.615753,1.116243,8.082939,1.395284
18,CPLE3,IBEP,2026-07-13,COPEL,ON NM,2.969407e+09,2.154,0.066665,-0.061209,-0.055854,-6.865520,41.238568,0.837125,3.075152,2.515007
0,ABEV3,IBEP,2026-07-13,AMBEV S/A,ON,4.273841e+09,3.158,-0.025933,-0.071207,-0.043674,-7.870372,30.967349,0.649612,1.752825,-0.759527
7,BBDC3,IBEP,2026-07-13,BRADESCO,ON EJ N1,1.464429e+09,1.126,0.047058,0.018216,0.014350,-8.443798,32.045110,1.136367,3.124310,1.349577
17,CPFE3,IBEP,2026-07-13,CPFL ENERGIA,ON NM,1.877325e+08,0.420,0.074074,-0.976628,-0.976628,-8.497768,22.618477,0.596883,1.915986,2.414884
37,ITUB4,IBEP,2026-07-13,ITAUUNIBANCO,PN N1,5.349695e+09,11.069,0.011946,0.422955,0.098618,-8.519084,43.879179,0.998300,2.945250,2.729977
10,BPAC11,IBEP,2026-07-13,BTGP BANCO,UNT N2,1.194625e+09,3.277,0.046562,0.155469,0.032909,-8.719299,28.164462,1.274018,6.030667,5.114554
28,EQTL3,IBEP,2026-07-13,EQUATORIAL,ON NM,1.247729e+09,2.384,0.005551,NaN,NaN,-9.790515,10.032838,0.745647,4.998826,-0.575592
8,BBDC4,IBEP,2026-07-13,BRADESCO,PN EJ N1,5.100890e+09,4.493,0.047058,0.018216,0.014350,-9.817985,28.552433,1.149982,2.594156,2.109510
27,ENGI11,IBEP,2026-07-13,ENERGISA,UNT N2,3.255030e+08,0.792,0.012670,-0.243111,-0.106840,-10.369738,11.233370,0.770017,2.552502,0.751817
71,^BVSP,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-10.465778,16.203084,1.000000,3.172459,1.291160
3,AURE3,IBEP,2026-07-13,AUREN,ON NM,3.177999e+08,0.193,0.003871,0.695373,-0.132830,-10.814510,20.892407,0.410479,0.313306,4.528488
24,EGIE3,IBEP,2026-07-13,ENGIE BRASIL,ON NM,3.573105e+08,0.560,0.099239,0.788275,0.681758,-11.343260,5.541124,0.581208,1.979771,-0.743651
55,SBSP3,IBEP,2026-07-13,SABESP,ON NM,3.506733e+09,5.095,0.108769,0.020655,-0.116366,-11.639399,51.459778,0.966768,4.830111,-0.269285
34,IGTI11,IBEP,2026-07-13,IGUATEMI S.A,UNT N1,2.058010e+08,0.255,0.029292,-0.136129,-0.118724,-12.508227,7.290617,0.715484,0.954695,2.962466
68,VIVT3,IBEP,2026-07-13,TELEF BRASIL,ON,7.071257e+08,1.181,0.019331,0.010383,-0.008819,-13.080680,26.027618,0.531323,2.143735,1.365000
42,MOTV3,IBEP,2026-07-13,MOTIVA SA,ON NM,1.002197e+09,0.709,NaN,NaN,NaN,-13.664056,16.367531,1.118650,2.235275,-0.054804
44,MULT3,IBEP,2026-07-13,MULTIPLAN,ON N2,3.200222e+08,0.453,0.011417,-0.444003,-0.455867,-13.755784,17.398781,1.076317,2.879706,-1.946688
11,BRAP4,IBEP,2026-07-13,BRADESPAR,PN N1,2.509147e+08,0.254,-0.016141,NaN,NaN,-14.868572,3.221853,0.923126,4.123928,-1.230013
69,WEGE3,IBEP,2026-07-13,WEG,ON NM,1.485955e+09,3.228,0.032812,NaN,NaN,-15.712696,-6.563231,0.748077,9.288989,1.159139
21,CURY3,IBEP,2026-07-13,CURY S/A,ON NM,1.609882e+08,0.258,0.104395,-1.919004,-0.334183,-16.474071,13.594011,0.742573,5.841309,2.415978
15,CMIN3,IBEP,2026-07-13,CSNMINERACAO,ON N2,1.646519e+09,0.402,0.030336,-0.242544,-0.218190,-17.030889,3.467106,0.740547,3.698284,-1.105217
64,VALE3,IBEP,2026-07-13,VALE,ON NM,4.268647e+09,14.789,-0.031397,-0.242255,-0.180473,-17.660114,3.115167,0.919425,2.301248,-1.171648
38,KLBN11,IBEP,2026-07-13,KLABIN S/A,UNT N2,8.045726e+08,0.659,-0.031637,-0.545447,-0.041675,-18.149228,-10.018008,0.449159,1.748381,3.697030
25,EMBJ3,IBEP,2026-07-13,EMBRAER,ON NM,7.118331e+08,2.813,-0.013919,-0.593536,-0.541634,-18.319558,53.735393,0.908156,-0.554345,5.170099
60,TIMS3,IBEP,2026-07-13,TIM,ON NM,7.774511e+08,0.827,-0.000309,-0.035122,-0.035122,-18.540826,24.575720,0.695374,3.391903,1.482672
4,AXIA3,IBEP,2026-07-13,AXIA ENERGIA,ON NM,2.156760e+09,5.443,0.006771,0.000000,0.000000,-19.538351,13.432179,1.303794,8.393945,8.475440
6,B3SA3,IBEP,2026-07-13,B3,ON NM,4.997060e+09,3.599,-0.001699,0.086040,0.087415,-21.117412,4.717595,1.199999,3.924473,0.013237
23,DIRR3,IBEP,2026-07-13,DIRECIONAL,ON NM,3.270916e+08,0.203,0.151654,-0.050195,-0.012943,-21.650529,28.062303,1.075939,6.626048,0.905132
47,PRIO3,IBEP,2026-07-13,PRIO,ON NM,7.572656e+08,1.961,0.030502,NaN,NaN,-23.092924,5.350241,1.137179,8.461353,4.729404
54,SANB11,IBEP,2026-07-13,SANTANDER BR,UNT,3.603472e+08,0.465,0.020907,0.437722,0.101965,-25.078934,-4.057208,1.067378,2.456071,3.468466
46,POMO4,IBEP,2026-07-13,MARCOPOLO,PN N2,7.282662e+08,0.198,-0.031629,-0.540538,-0.443393,-26.631150,8.949790,0.914676,2.859294,6.557092
56,SLCE3,IBEP,2026-07-13,SLC AGRICOLA,ON NM,2.204037e+08,0.144,-0.051183,0.453835,-0.059302,-27.432709,-24.540661,0.477767,2.838122,1.444904
57,SMFT3,IBEP,2026-07-13,SMART FIT,ON NM,5.566513e+08,0.551,0.102864,0.238072,0.130604,-27.495621,-2.937802,0.837709,-0.458382,9.958411
29,FLRY3,IBEP,2026-07-13,FLEURY,ON NM,4.471508e+08,0.343,0.019770,0.345059,0.101225,-28.755897,22.645516,0.776747,4.504383,3.294996
1,ALOS3,IBEP,2026-07-13,ALLOS,ON NM,4.785587e+08,0.641,-0.010839,0.099930,-0.203833,-31.465675,32.616056,1.007243,4.596409,1.372958
67,VIVA3,IBEP,2026-07-13,VIVARA S.A.,ON NM,1.236983e+08,0.136,0.019249,NaN,NaN,-33.442469,-8.934510,1.409680,2.470710,7.233917
49,RADL3,IBEP,2026-07-13,RAIADROGASIL,ON EDJ NM,1.313916e+09,1.152,0.000799,-0.030909,-0.069610,-33.619199,-24.191056,0.626204,5.067682,2.123071
22,CYRE3,IBEP,2026-07-13,CYRELA REALT,ON ATZ NM,2.816093e+08,0.303,0.021727,0.074324,0.247089,-34.683792,-2.567143,1.410750,7.185039,2.120891
53,RENT3,IBEP,2026-07-13,LOCALIZA,ON NM,9.784790e+08,1.878,-0.032858,-0.063132,0.029917,-35.062858,-23.748142,1.245523,5.125719,-0.219866
61,TOTS3,IBEP,2026-07-13,TOTVS,ON NM,5.339974e+08,0.746,0.369476,0.067323,0.077533,-36.935477,-24.375297,0.850483,3.794025,3.421849
58,SUZB3,IBEP,2026-07-13,SUZANO S.A.,ON NM,6.129185e+08,1.189,0.000043,-0.207931,-0.135792,-39.903521,-29.049404,0.281647,0.391985,3.213658
50,RAIL3,IBEP,2026-07-13,RUMO S.A.,ON NM,1.221155e+09,0.819,0.014921,-0.462707,-0.182916,-43.333140,-30.102266,1.032417,5.670514,0.618539
51,RDOR3,IBEP,2026-07-13,REDE D OR,ON NM,1.091469e+09,1.836,0.034045,-0.047052,-0.002775,-43.394346,46.542416,0.715456,3.291349,3.280893
40,MBRF3,IBEP,2026-07-13,MARFRIG,ON NM,7.611753e+08,0.553,-0.008779,-0.141310,-0.018615,-43.495640,-7.498601,0.843689,0.452286,6.596810
14,CEAB3,IBEP,2026-07-13,CEA MODAS,ON NM,2.049643e+08,0.102,-0.073862,-0.379730,-0.360655,-46.146366,4.742725,1.606240,-2.443676,4.945588
33,HYPE3,IBEP,2026-07-13,HYPERA,ON NM,3.210839e+08,0.317,0.040196,-0.071719,-0.092919,-51.383980,-26.046361,0.782824,2.965961,-2.007957
63,USIM5,IBEP,2026-07-13,USIMINAS,PNA N1,5.182568e+08,0.205,-0.025669,1.331015,-0.038451,-55.873298,0.858527,1.320701,9.270934,1.050666
2,ASAI3,IBEP,2026-07-13,ASSAI,ON NM,1.338623e+09,0.555,-0.013089,-0.025180,-0.103813,-56.468377,19.493716,0.695947,-1.737464,1.614220
52,RECV3,IBEP,2026-07-13,PETRORECSA,ON NM,2.746249e+08,0.131,0.043988,-0.036582,-0.039748,-57.585714,-18.865875,0.659329,2.378263,1.551733
12,BRAV3,IBEP,2026-07-13,BRAVA,ON NM,4.628830e+08,0.409,-0.000408,1.135116,0.287014,-61.831939,13.437100,0.686827,1.824885,0.652867
39,LREN3,IBEP,2026-07-13,LOJAS RENNER,ON NM,9.825937e+08,0.671,-0.035445,-0.329312,-0.334379,-63.369198,-4.205071,1.217397,0.437852,1.392879
9,BEEF3,IBEP,2026-07-13,MINERVA,ON NM,4.548049e+08,0.078,-0.052874,-0.082512,-0.085922,-75.128103,-47.844065,0.639468,2.274367,0.131277
43,MRVE3,IBEP,2026-07-13,MRV,ON NM,3.746814e+08,0.088,0.000370,0.024825,-0.075280,-75.253485,-38.461136,1.233082,4.941720,0.395679
5,AZZA3,IBEP,2026-07-13,AZZAS 2154,ON NM,1.095713e+08,0.098,0.018336,-0.274795,-0.314726,-78.499199,-61.825492,1.021932,2.080288,1.406378
65,VAMO3,IBEP,2026-07-13,VAMOS,ON NM,4.480521e+08,0.064,0.006114,-0.072400,0.082968,-80.199713,-6.224733,1.008733,9.472179,-2.612406
70,YDUQ3,IBEP,2026-07-13,YDUQS PART,ON NM,2.613658e+08,0.110,-0.065059,NaN,NaN,-81.474097,-29.731063,1.288252,4.305504,-5.061230
19,CSAN3,IBEP,2026-07-13,COSAN,ON NM,2.242672e+09,0.426,-0.240300,NaN,NaN,-83.446060,-69.994970,1.131510,5.351306,-1.659304
20,CSNA3,IBEP,2026-07-13,SID NACIONAL,ON,7.279750e+08,0.176,-0.034032,-0.756444,-0.045856,-84.694356,-60.686205,1.447781,7.773735,-5.094953
16,COGN3,IBEP,2026-07-13,COGNA ON,ON NM,1.915914e+09,0.215,-0.005607,NaN,NaN,-85.988631,-468.027769,1.353228,4.399647,-6.604558
45,NATU3,IBEP,2026-07-13,NATURA,ON NM,8.383595e+08,0.340,0.009475,NaN,NaN,-87.416620,-59.464713,0.708835,-9.886698,4.102211
13,BRKM5,IBEP,2026-07-13,BRASKEM,PNA N1,2.657097e+08,0.082,-0.093405,-0.001645,-0.065572,-88.893232,-59.848197,1.094264,0.174663,0.949285
32,HAPV3,IBEP,2026-07-13,HAPVIDA,ON NM,2.716623e+08,0.134,0.004967,NaN,NaN,-96.106825,-67.431153,1.187538,2.489505,6.843014
41,MGLU3,IBEP,2026-07-13,MAGAZ LUIZA,ON ATZ NM,3.731551e+08,0.091,-0.018975,-0.028987,-0.146307,-97.776386,-85.310416,1.495497,6.419541,15.375055

In [6]:
df_final[df_final["Part. (%)"] > 5]

,Código,Indice,Data Referencia,Ação,Tipo,Qtde. Teórica,Part. (%),Ativo Total,Resultado Bruto,Receita de Vendas,Drawdown Atual,Resíduo Regressão Linear,Beta,Retorno Agrupado por Mês (Média Mês:7),Retorno Agrupado por Mês (Média Mês:8)
37,ITUB4,IBEP,2026-07-13,ITAUUNIBANCO,PN N1,5.349695e+09,11.069,0.011946,0.422955,0.098618,-8.519106,43.879179,0.998299,2.945274,2.729987
55,SBSP3,IBEP,2026-07-13,SABESP,ON NM,3.506733e+09,5.095,0.108769,0.020655,-0.116366,-11.639399,51.459778,0.966768,4.830103,-0.269287
64,VALE3,IBEP,2026-07-13,VALE,ON NM,4.268647e+09,14.789,-0.031397,-0.242255,-0.180473,-17.660114,3.115167,0.919426,2.301236,-1.171640
4,AXIA3,IBEP,2026-07-13,AXIA ENERGIA,ON NM,2.156760e+09,5.443,0.006771,0.000000,0.000000,-19.538351,13.432179,1.303794,8.393941,8.475445