In [2]:
from pipelines.readers.b3_indices_segmentos_setoriais import ReaderSQLB3IndicesSegmentosSetoriais
from pipelines.readers.cvm_balanco_patrimonial import ReaderCSVCVMBalancoPatrimonial

from yfinance import download
import plotly.express as px
import numpy as np
import pandas as pd
from datetime import date

In [3]:
reader_b3_segmentos_setoriais = ReaderSQLB3IndicesSegmentosSetoriais()
df_b3_segmentos_setoriais = reader_b3_segmentos_setoriais.read(indice="IBEP")

print(df_b3_segmentos_setoriais.shape)
df_b3_segmentos_setoriais.tail(3)

(71, 7)

,Indice,Data Referencia,Código,Ação,Tipo,Qtde. Teórica,Part. (%)
68,IBEP,2026-07-06,VIVT3,TELEF BRASIL,ON EJ,707125712,1.166
69,IBEP,2026-07-06,WEGE3,WEG,ON NM,1485954732,3.278
70,IBEP,2026-07-06,YDUQ3,YDUQS PART,ON NM,261365845,0.112

In [4]:
tickers = list(df_b3_segmentos_setoriais["Código"]) + ["^BVSP"]

In [8]:
reader_csv_balanco_patrimonial = ReaderCSVCVMBalancoPatrimonial()

data = {}

benchmark = download("^BVSP", period="10y", interval="1d", progress=False, auto_adjust=False).droplevel(1, axis=1)[["Adj Close"]].pct_change()

for codigo in tickers:
    
    # Balanco Patrimonial
    try:
        ativo_total = reader_csv_balanco_patrimonial.read(ticker=codigo, tipo_arquivo="BPA_ind", cd_conta="1").astype(int).pct_change().iloc[:, 1].iloc[-1]
    except Exception:
        ativo_total = np.nan
    try:
        resultado_bruto = reader_csv_balanco_patrimonial.read(ticker=codigo, tipo_arquivo="DRE_ind", cd_conta="3.03").astype(int).pct_change().iloc[:, 1].iloc[-1]
    except Exception:
        resultado_bruto = np.nan    
    try:
        receita_de_vendas = reader_csv_balanco_patrimonial.read(ticker=codigo, tipo_arquivo="DRE_ind", cd_conta="3.01").astype(int).pct_change().iloc[:, 1].iloc[-1]
    except Exception:
        receita_de_vendas = np.nan

    try:
        serie_precos = download(codigo + ".SA" if codigo != "^BVSP" else codigo, period="10y", interval="1d", progress=False, auto_adjust=False).droplevel(1, axis=1)
    except Exception:
        
        drawdown_atual = np.nan
        residuo_reg_lin = np.nan

        continue
    
    # Drawdown
    preco_maximo = serie_precos['Adj Close'].max()
    preco_atual = serie_precos['Adj Close'].iloc[-1]
    drawdown_atual = (preco_atual - preco_maximo) / preco_maximo * 100
    
    # Regressão linear
    y = serie_precos["Adj Close"].to_numpy()
    x = np.arange(len(y))

    coef = np.polyfit(x, y, 1)      
    tendencia = np.polyval(coef, x)

    residuo_reg_lin = ((serie_precos["Adj Close"] - tendencia) / tendencia) * 100
    residuo_reg_lin = residuo_reg_lin.iloc[-1]
    
    # Beta
    beta = serie_precos["Adj Close"].pct_change().cov(benchmark["Adj Close"]) / benchmark["Adj Close"].var()
    
    # Retorno agrupado por mês
    serie_precos['ret'] = serie_precos["Adj Close"].pct_change()
    serie_precos['mes'] = serie_precos.index.month
    serie_precos['ano'] = serie_precos.index.year

    tabela = (
        serie_precos.groupby(['ano', 'mes'])[['ret']]
        .sum()
        .reset_index()
        .pivot(index='ano', columns='mes', values='ret')
    )
    
    data[codigo] = {
        "Ativo Total": ativo_total,
        "Resultado Bruto": resultado_bruto,
        "Receita de Vendas": receita_de_vendas,
        "Drawdown Atual": drawdown_atual,
        "Resíduo Regressão Linear": residuo_reg_lin,
        "Beta": beta,
        f"Retorno Agrupado por Mês (Média Mês:{date.today().month})": tabela[date.today().month].mean()
        }

In [11]:
df_final = (
    df_b3_segmentos_setoriais.set_index("Código")
    .join(pd.DataFrame.from_dict(data, orient="index"))
    .reset_index()
)

benchmark_row = pd.DataFrame([{
    "Código": "^BVSP",
    "Ativo Total": np.nan,
    "Resultado Bruto": np.nan,
    "Receita de Vendas": np.nan,
    "Drawdown Atual": data["^BVSP"]["Drawdown Atual"],
    "Resíduo Regressão Linear": data["^BVSP"]["Resíduo Regressão Linear"],
    "Beta": data["^BVSP"]["Beta"],
    f"Retorno Agrupado por Mês (Média Mês:{date.today().month})": data["^BVSP"][f"Retorno Agrupado por Mês (Média Mês:{date.today().month})"]
}])

df_final = pd.concat([df_final, benchmark_row], ignore_index=True)

pd.set_option("display.max_rows", None)
df_final.sort_values(by="Drawdown Atual", ascending=False)

,Código,Indice,Data Referencia,Ação,Tipo,Qtde. Teórica,Part. (%),Ativo Total,Resultado Bruto,Receita de Vendas,Drawdown Atual,Resíduo Regressão Linear,Beta,Retorno Agrupado por Mês (Média Mês:7)
48,PSSA3,IBEP,2026-07-06,PORTO SEGURO,ON NM,1.788254e+08,0.460,0.056534,NaN,NaN,-2.690218,36.546325,0.539686,0.036751
26,ENEV3,IBEP,2026-07-06,ENEVA,ON NM,1.913352e+09,2.418,0.041386,-0.340257,-0.268461,-3.479525,40.196312,0.747599,0.046497
59,TAEE11,IBEP,2026-07-06,TAESA,UNT N2,2.185682e+08,0.426,0.035111,0.030653,0.020434,-7.238636,8.467384,0.449122,0.042146
0,ABEV3,IBEP,2026-07-06,AMBEV S/A,ON,4.273841e+09,3.304,-0.025933,-0.071207,-0.043674,-7.520953,31.701762,0.650153,0.018904
62,UGPA3,IBEP,2026-07-06,ULTRAPAR,ON NM,1.067870e+09,1.395,0.045903,NaN,NaN,-8.960573,40.189207,1.195638,0.002465
31,GOAU4,IBEP,2026-07-06,GERDAU MET,PN N1,8.308378e+08,0.374,-0.011312,0.288102,-0.209715,-8.987699,8.287816,1.190810,0.086045
36,ITSA4,IBEP,2026-07-06,ITAUSA,PN N1,5.970738e+09,3.853,0.028099,NaN,NaN,-9.135634,39.756540,0.968089,0.036002
18,CPLE3,IBEP,2026-07-06,COPEL,ON NM,2.969407e+09,2.122,0.066665,-0.061209,-0.055854,-10.463758,36.391668,0.837723,0.034592
66,VBBR3,IBEP,2026-07-06,VIBRA,ON NM,1.192005e+09,1.718,0.043912,0.248137,-0.049013,-10.509477,42.134707,1.171826,0.036983
11,BRAP4,IBEP,2026-07-06,BRADESPAR,PN N1,2.509147e+08,0.267,-0.016141,NaN,NaN,-12.004706,6.922039,0.923714,0.047761
37,ITUB4,IBEP,2026-07-06,ITAUUNIBANCO,PN EJ N1,5.349695e+09,10.850,0.011946,0.422955,0.098618,-12.112242,38.711435,0.997588,0.029971
64,VALE3,IBEP,2026-07-06,VALE,ON ATZ NM,4.268647e+09,15.970,-0.031397,-0.242255,-0.180473,-12.487513,9.786624,0.919936,0.031634
17,CPFE3,IBEP,2026-07-06,CPFL ENERGIA,ON NM,1.877325e+08,0.407,0.074074,-0.976628,-0.976628,-12.664780,17.399472,0.594870,0.016318
35,ISAE4,IBEP,2026-07-06,ISA ENERGIA,PN N1,4.155688e+08,0.545,0.013029,-0.013623,-0.173816,-12.791392,7.876148,0.487183,0.009175
30,GGBR4,IBEP,2026-07-06,GERDAU,PN N1,1.258208e+09,1.280,-0.011312,0.288102,-0.209715,-13.022309,0.451185,1.117945,0.076313
71,^BVSP,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13.193092,12.848995,1.000000,0.032430
10,BPAC11,IBEP,2026-07-06,BTGP BANCO,UNT N2,1.194625e+09,3.166,0.046562,0.155469,0.032909,-13.211061,22.357003,1.272669,0.055045
7,BBDC3,IBEP,2026-07-06,BRADESCO,ON EJ N1,1.464429e+09,1.085,0.047058,0.018216,0.014350,-13.424089,25.097047,1.135512,0.028573
55,SBSP3,IBEP,2026-07-06,SABESP,ON NM,3.506733e+09,5.054,0.108769,0.020655,-0.116366,-13.741193,48.760274,0.966615,0.049176
28,EQTL3,IBEP,2026-07-06,EQUATORIAL,ON NM,1.247729e+09,2.335,0.005551,NaN,NaN,-13.869895,5.257606,0.743462,0.046772
8,BBDC4,IBEP,2026-07-06,BRADESCO,PN EJ N1,5.100890e+09,4.351,0.047058,0.018216,0.014350,-14.345728,22.301918,1.149518,0.025025
34,IGTI11,IBEP,2026-07-06,IGUATEMI S.A,UNT N1,2.058010e+08,0.252,0.029292,-0.136129,-0.118724,-15.075708,4.344682,0.710137,0.003214
24,EGIE3,IBEP,2026-07-06,ENGIE BRASIL,ON NM,3.573105e+08,0.545,0.099239,0.788275,0.681758,-15.145104,1.141517,0.580562,0.018554
42,MOTV3,IBEP,2026-07-06,MOTIVA SA,ON NM,1.002197e+09,0.705,NaN,NaN,NaN,-15.487651,14.079325,1.118622,0.024457
68,VIVT3,IBEP,2026-07-06,TELEF BRASIL,ON EJ,7.071257e+08,1.166,0.019331,0.010383,-0.008819,-16.119817,21.967162,0.530804,0.022904
69,WEGE3,IBEP,2026-07-06,WEG,ON NM,1.485955e+09,3.278,0.032812,NaN,NaN,-16.165756,-6.952678,0.747122,0.092408
44,MULT3,IBEP,2026-07-06,MULTIPLAN,ON EJ N2,3.200222e+08,0.446,0.011417,-0.444003,-0.455867,-16.432241,13.966770,1.074997,0.028416
27,ENGI11,IBEP,2026-07-06,ENERGISA,UNT N2,3.255030e+08,0.750,0.012670,-0.243111,-0.106840,-16.474637,3.819743,0.767618,0.019562
21,CURY3,IBEP,2026-07-06,CURY S/A,ON NM,1.609882e+08,0.267,0.104395,-1.919004,-0.334183,-17.475112,12.677090,0.736545,0.055531
3,AURE3,IBEP,2026-07-06,AUREN,ON NM,3.177999e+08,0.181,0.003871,0.695373,-0.132830,-17.796027,11.666812,0.399449,-0.014056
25,EMBJ3,IBEP,2026-07-06,EMBRAER,ON NM,7.118331e+08,2.866,-0.013919,-0.593536,-0.541634,-18.097492,55.239529,0.907767,-0.005698
23,DIRR3,IBEP,2026-07-06,DIRECIONAL,ON NM,3.270916e+08,0.222,0.151654,-0.050195,-0.012943,-18.110641,34.393273,1.074304,0.075371
60,TIMS3,IBEP,2026-07-06,TIM,ON NM,7.774511e+08,0.841,-0.000309,-0.035122,-0.035122,-19.542082,23.403612,0.696394,0.039669
38,KLBN11,IBEP,2026-07-06,KLABIN S/A,UNT N2,8.045726e+08,0.653,-0.031637,-0.545447,-0.041675,-20.202492,-12.272360,0.447555,0.009967
4,AXIA3,IBEP,2026-07-06,AXIA ENERGIA,ON NM,2.156760e+09,5.524,0.006771,0.000000,0.000000,-20.268057,12.617453,1.305663,0.093639
6,B3SA3,IBEP,2026-07-06,B3,ON EJ NM,4.997060e+09,3.500,-0.001699,0.086040,0.087415,-25.414519,-0.919313,1.198923,0.038696
47,PRIO3,IBEP,2026-07-06,PRIO,ON NM,7.572656e+08,1.903,0.030502,NaN,NaN,-25.700415,2.059626,1.138405,0.084922
54,SANB11,IBEP,2026-07-06,SANTANDER BR,UNT,3.603472e+08,0.461,0.020907,0.437722,0.101965,-26.896353,-6.441180,1.066280,0.028180
46,POMO4,IBEP,2026-07-06,MARCOPOLO,PN N2,7.282662e+08,0.206,-0.031629,-0.540538,-0.443393,-27.515118,7.898250,0.914184,0.031202
57,SMFT3,IBEP,2026-07-06,SMART FIT,ON NM,5.566513e+08,0.532,0.102864,0.238072,0.130604,-30.988980,-7.640396,0.831983,-0.013205
15,CMIN3,IBEP,2026-07-06,CSNMINERACAO,ON N2,1.646519e+09,0.337,0.030336,-0.242544,-0.218190,-31.625833,-14.702914,0.734623,0.003829
29,FLRY3,IBEP,2026-07-06,FLEURY,ON NM,4.471508e+08,0.334,0.019770,0.345059,0.101225,-31.793105,17.351801,0.776812,0.046631
1,ALOS3,IBEP,2026-07-06,ALLOS,ON NM,4.785587e+08,0.640,-0.010839,0.099930,-0.203833,-32.659653,30.569516,1.004679,0.044140
56,SLCE3,IBEP,2026-07-06,SLC AGRICOLA,ON NM,2.204037e+08,0.134,-0.051183,0.453835,-0.059302,-33.747410,-31.130081,0.476920,0.021661
67,VIVA3,IBEP,2026-07-06,VIVARA S.A.,ON NM,1.236983e+08,0.134,0.019249,NaN,NaN,-35.592224,-11.961617,1.409400,0.019824
22,CYRE3,IBEP,2026-07-06,CYRELA REALT,ON NM,2.816093e+08,0.313,0.021727,0.074324,0.247089,-36.015040,-4.484539,1.408481,0.072104
53,RENT3,IBEP,2026-07-06,LOCALIZA,ON EJ NM,9.784790e+08,1.925,-0.032858,-0.063132,0.029917,-36.295251,-25.277321,1.244575,0.052709
61,TOTS3,IBEP,2026-07-06,TOTVS,ON NM,5.339974e+08,0.760,0.369476,0.067323,0.077533,-36.745714,-24.167441,0.849516,0.038780
49,RADL3,IBEP,2026-07-06,RAIADROGASIL,ON EDJ NM,1.313916e+09,1.058,0.000799,-0.030909,-0.069610,-40.040077,-31.616121,0.625554,0.043079
40,MBRF3,IBEP,2026-07-06,MARFRIG,ON NM,7.611753e+08,0.606,-0.008779,-0.141310,-0.018615,-40.370641,-2.265590,0.842757,0.009486
58,SUZB3,IBEP,2026-07-06,SUZANO S.A.,ON NM,6.129185e+08,1.187,0.000043,-0.207931,-0.135792,-41.103995,-30.543754,0.281011,0.002076
51,RDOR3,IBEP,2026-07-06,REDE D OR,ON EJ NM,1.091469e+09,1.852,0.034045,-0.047052,-0.002775,-44.997297,42.781341,0.713219,0.027954
50,RAIL3,IBEP,2026-07-06,RUMO S.A.,ON NM,1.221155e+09,0.790,0.014921,-0.462707,-0.182916,-46.213839,-33.838040,1.031437,0.057171
14,CEAB3,IBEP,2026-07-06,CEA MODAS,ON NM,2.049643e+08,0.107,-0.073862,-0.379730,-0.360655,-46.247218,4.621823,1.606544,-0.024945
33,HYPE3,IBEP,2026-07-06,HYPERA,ON EJ NM,3.210839e+08,0.320,0.040196,-0.071719,-0.092919,-52.351238,-27.660599,0.781221,0.031719
63,USIM5,IBEP,2026-07-06,USIMINAS,PNA N1,5.182568e+08,0.216,-0.025669,1.331015,-0.038451,-54.515552,3.847002,1.321442,0.095447
2,ASAI3,IBEP,2026-07-06,ASSAI,ON NM,1.338623e+09,0.558,-0.013089,-0.025180,-0.103813,-57.449924,16.557048,0.692935,-0.021390
52,RECV3,IBEP,2026-07-06,PETRORECSA,ON NM,2.746249e+08,0.126,0.043988,-0.036582,-0.039748,-59.992786,-23.792287,0.661917,0.013651
12,BRAV3,IBEP,2026-07-06,BRAVA,ON NM,4.628830e+08,0.393,-0.000408,1.135116,0.287014,-62.718632,10.506288,0.688986,0.014297
39,LREN3,IBEP,2026-07-06,LOJAS RENNER,ON NM,9.825937e+08,0.690,-0.035445,-0.329312,-0.334379,-64.697127,-7.963442,1.217974,0.007393
43,MRVE3,IBEP,2026-07-06,MRV,ON NM,3.746814e+08,0.097,0.000370,0.024825,-0.075280,-73.771656,-35.102397,1.233271,0.057353
9,BEEF3,IBEP,2026-07-06,MINERVA,ON NM,4.548049e+08,0.076,-0.052874,-0.082512,-0.085922,-76.147442,-50.181857,0.637200,0.019003
5,AZZA3,IBEP,2026-07-06,AZZAS 2154,ON NM,1.095713e+08,0.089,0.018336,-0.274795,-0.314726,-80.356596,-65.287617,1.021814,0.017649
70,YDUQ3,IBEP,2026-07-06,YDUQS PART,ON NM,2.613658e+08,0.112,-0.065059,NaN,NaN,-81.225706,-29.268958,1.287655,0.050626
65,VAMO3,IBEP,2026-07-06,VAMOS,ON NM,4.480521e+08,0.061,0.006114,-0.072400,0.082968,-81.429139,-13.134687,1.006197,0.083647
19,CSAN3,IBEP,2026-07-06,COSAN,ON NM,2.242672e+09,0.402,-0.240300,NaN,NaN,-84.381542,-71.834156,1.128775,0.049249
20,CSNA3,IBEP,2026-07-06,SID NACIONAL,ON,7.279750e+08,0.167,-0.034032,-0.756444,-0.045856,-85.758071,-63.591124,1.446362,0.071986
16,COGN3,IBEP,2026-07-06,COGNA ON,ON NM,1.915914e+09,0.210,-0.005607,NaN,NaN,-86.864344,-447.347528,1.351106,0.041554
45,NATU3,IBEP,2026-07-06,NATURA,ON ATZ NM,8.383595e+08,0.333,0.009475,NaN,NaN,-87.851530,-61.510318,0.708745,-0.105680
13,BRKM5,IBEP,2026-07-06,BRASKEM,PNA ATZ N1,2.657097e+08,0.079,-0.093405,-0.001645,-0.065572,-89.546572,-62.617218,1.091707,-0.004626
32,HAPV3,IBEP,2026-07-06,HAPVIDA,ON ATZ NM,2.716623e+08,0.137,0.004967,NaN,NaN,-96.187626,-68.550780,1.185702,0.022362
41,MGLU3,IBEP,2026-07-06,MAGAZ LUIZA,ON NM,3.731551e+08,0.079,-0.018975,-0.028987,-0.146307,-98.146989,-87.896302,1.493300,0.053194