In [10]:

from pipelines.readers.b3_indices_segmentos_setoriais import ReaderSQLB3IndicesSegmentosSetoriais
from pipelines.readers.cvm_balanco_patrimonial import ReaderCSVCVMBalancoPatrimonial

from yfinance import download
from numpy import nan, arange, polyfit, polyval
from pandas import DataFrame, set_option, concat, DateOffset
from datetime import date
from dateutil.relativedelta import relativedelta

In [11]:
reader_b3_segmentos_setoriais = ReaderSQLB3IndicesSegmentosSetoriais()
df_b3_segmentos_setoriais = reader_b3_segmentos_setoriais.read(indice="IBEP")

print(df_b3_segmentos_setoriais.shape)
df_b3_segmentos_setoriais.tail(3)

(71, 7)

,Indice,Data Referencia,Código,Ação,Tipo,Qtde. Teórica,Part. (%)
68,IBEP,2026-07-07,VIVT3,TELEF BRASIL,ON EJ,707125712,1.169
69,IBEP,2026-07-07,WEGE3,WEG,ON NM,1485954732,3.293
70,IBEP,2026-07-07,YDUQ3,YDUQS PART,ON NM,261365845,0.108

In [12]:
tickers = list(df_b3_segmentos_setoriais["Código"]) + ["^BVSP"]

In [13]:

reader_csv_balanco_patrimonial = ReaderCSVCVMBalancoPatrimonial()

data = {}

benchmark = download("^BVSP", period="10y", interval="1d", progress=False, auto_adjust=False).droplevel(1, axis=1)[["Adj Close"]].pct_change()

for codigo in tickers:
    
    # Balanco Patrimonial
    try:
        ativo_total = reader_csv_balanco_patrimonial.read(ticker=codigo, tipo_arquivo="BPA_ind", cd_conta="1").astype(int).pct_change().iloc[:, 1].iloc[-1]
    except Exception:
        ativo_total = nan
    try:
        resultado_bruto = reader_csv_balanco_patrimonial.read(ticker=codigo, tipo_arquivo="DRE_ind", cd_conta="3.03").astype(int).pct_change().iloc[:, 1].iloc[-1]
    except Exception:
        resultado_bruto = nan    
    try:
        receita_de_vendas = reader_csv_balanco_patrimonial.read(ticker=codigo, tipo_arquivo="DRE_ind", cd_conta="3.01").astype(int).pct_change().iloc[:, 1].iloc[-1]
    except Exception:
        receita_de_vendas = nan

    try:
        serie_precos = download(codigo + ".SA" if codigo != "^BVSP" else codigo, period="10y", interval="1d", progress=False, auto_adjust=False).droplevel(1, axis=1)
    except Exception:
        
        drawdown_atual = nan
        residuo_reg_lin = nan

        continue
    
    # Drawdown
    preco_maximo = serie_precos['Adj Close'].max()
    preco_atual = serie_precos['Adj Close'].iloc[-1]
    drawdown_atual = (preco_atual - preco_maximo) / preco_maximo * 100
    
    # Regressão linear
    y = serie_precos["Adj Close"].to_numpy()
    x = arange(len(y))

    coef = polyfit(x, y, 1)      
    tendencia = polyval(coef, x)

    residuo_reg_lin = ((serie_precos["Adj Close"] - tendencia) / tendencia) * 100
    residuo_reg_lin = residuo_reg_lin.iloc[-1]
    
    # Beta
    beta = serie_precos["Adj Close"].pct_change().cov(benchmark["Adj Close"]) / benchmark["Adj Close"].var()
    
    # Retorno agrupado por mês
    serie_precos['ret'] = serie_precos["Adj Close"].pct_change()
    serie_precos['mes'] = serie_precos.index.month
    serie_precos['ano'] = serie_precos.index.year

    tabela = (
        serie_precos.groupby(['ano', 'mes'])[['ret']]
        .sum()
        .reset_index()
        .pivot(index='ano', columns='mes', values='ret')
    ) * 100
    
    data[codigo] = {
        "Ativo Total": ativo_total,
        "Resultado Bruto": resultado_bruto,
        "Receita de Vendas": receita_de_vendas,
        "Drawdown Atual": drawdown_atual,
        "Resíduo Regressão Linear": residuo_reg_lin,
        "Beta": beta,
        f"Retorno Agrupado por Mês (Média Mês:{date.today().month})": tabela[date.today().month].mean(),
        f"Retorno Agrupado por Mês (Média Mês:{(date.today() + relativedelta(months=1)).month})": tabela[(date.today() + relativedelta(months=1)).month].mean()
        }

In [16]:
df_final = (
    df_b3_segmentos_setoriais.set_index("Código")
    .join(DataFrame.from_dict(data, orient="index"))
    .reset_index()
)

benchmark_row = DataFrame([{
    "Código": "^BVSP",
    "Ativo Total": nan,
    "Resultado Bruto": nan,
    "Receita de Vendas": nan,
    "Drawdown Atual": data["^BVSP"]["Drawdown Atual"],
    "Resíduo Regressão Linear": data["^BVSP"]["Resíduo Regressão Linear"],
    "Beta": data["^BVSP"]["Beta"],
    f"Retorno Agrupado por Mês (Média Mês:{date.today().month})": data["^BVSP"][f"Retorno Agrupado por Mês (Média Mês:{date.today().month})"],
    f"Retorno Agrupado por Mês (Média Mês:{(date.today() + relativedelta(months=1)).month})": data["^BVSP"][f"Retorno Agrupado por Mês (Média Mês:{(date.today() + relativedelta(months=1)).month})"]
}])

df_final = concat([df_final, benchmark_row], ignore_index=True)

set_option("display.max_rows", None)
df_final =  df_final.sort_values(by="Drawdown Atual", ascending=False)
df_final

,Código,Indice,Data Referencia,Ação,Tipo,Qtde. Teórica,Part. (%),Ativo Total,Resultado Bruto,Receita de Vendas,Drawdown Atual,Resíduo Regressão Linear,Beta,Retorno Agrupado por Mês (Média Mês:7),Retorno Agrupado por Mês (Média Mês:8)
48,PSSA3,IBEP,2026-07-07,PORTO SEGURO,ON NM,1.788254e+08,0.457,0.056534,NaN,NaN,-4.785843,33.482209,0.539791,3.395100,5.421270
26,ENEV3,IBEP,2026-07-07,ENEVA,ON NM,1.913352e+09,2.392,0.041386,-0.340257,-0.268461,-7.357741,34.314900,0.747984,4.569565,4.708633
0,ABEV3,IBEP,2026-07-07,AMBEV S/A,ON,4.273841e+09,3.251,-0.025933,-0.071207,-0.043674,-7.520942,31.639336,0.650159,1.928327,-0.759528
59,TAEE11,IBEP,2026-07-07,TAESA,UNT N2,2.185682e+08,0.421,0.035111,0.030653,0.020434,-7.645196,7.885899,0.449320,4.269298,1.427716
62,UGPA3,IBEP,2026-07-07,ULTRAPAR,ON NM,1.067870e+09,1.429,0.045903,NaN,NaN,-8.895410,40.134033,1.195599,0.179374,0.262500
36,ITSA4,IBEP,2026-07-07,ITAUSA,PN N1,5.970738e+09,3.850,0.028099,NaN,NaN,-9.000617,39.835087,0.968049,3.541159,2.173550
31,GOAU4,IBEP,2026-07-07,GERDAU MET,PN N1,8.308378e+08,0.383,-0.011312,0.288102,-0.209715,-9.176910,8.016687,1.190893,8.805200,3.311804
18,CPLE3,IBEP,2026-07-07,COPEL,ON NM,2.969407e+09,2.123,0.066665,-0.061209,-0.055854,-10.523730,36.145997,0.837719,3.430206,2.515005
66,VBBR3,IBEP,2026-07-07,VIBRA,ON NM,1.192005e+09,1.720,0.043912,0.248137,-0.049013,-11.222554,40.858821,1.171303,3.609765,5.750550
30,GGBR4,IBEP,2026-07-07,GERDAU,PN N1,1.258208e+09,1.316,-0.011312,0.288102,-0.209715,-11.399592,2.257778,1.117174,7.993405,1.395292
37,ITUB4,IBEP,2026-07-07,ITAUUNIBANCO,PN EJ N1,5.349695e+09,10.907,0.011946,0.422955,0.098618,-11.678588,39.275659,0.997519,2.950454,2.729995
35,ISAE4,IBEP,2026-07-07,ISA ENERGIA,PN N1,4.155688e+08,0.549,0.013029,-0.013623,-0.173816,-12.506810,8.175046,0.487185,1.015064,0.623694
17,CPFE3,IBEP,2026-07-07,CPFL ENERGIA,ON NM,1.877325e+08,0.404,0.074074,-0.976628,-0.976628,-12.894155,16.954275,0.594874,1.445880,2.414882
7,BBDC3,IBEP,2026-07-07,BRADESCO,ON EJ N1,1.464429e+09,1.091,0.047058,0.018216,0.014350,-13.227408,25.288667,1.135041,2.840761,1.349586
71,^BVSP,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13.418260,12.513182,1.000000,3.199644,1.291160
24,EGIE3,IBEP,2026-07-07,ENGIE BRASIL,ON NM,3.573105e+08,0.551,0.099239,0.788275,0.681758,-13.428992,3.155031,0.580416,1.987974,-0.743650
28,EQTL3,IBEP,2026-07-07,EQUATORIAL,ON NM,1.247729e+09,2.335,0.005551,NaN,NaN,-13.847848,5.235302,0.743417,4.562807,-0.575594
8,BBDC4,IBEP,2026-07-07,BRADESCO,PN EJ N1,5.100890e+09,4.379,0.047058,0.018216,0.014350,-14.025862,22.674888,1.149015,2.501026,2.109522
11,BRAP4,IBEP,2026-07-07,BRADESPAR,PN N1,2.509147e+08,0.267,-0.016141,NaN,NaN,-14.358572,3.965608,0.923748,4.754455,-1.230010
10,BPAC11,IBEP,2026-07-07,BTGP BANCO,UNT N2,1.194625e+09,3.170,0.046562,0.155469,0.032909,-14.594337,20.213793,1.271841,5.344443,5.114562
64,VALE3,IBEP,2026-07-07,VALE,ON ATZ NM,4.268647e+09,15.907,-0.031397,-0.242255,-0.180473,-15.384608,6.065064,0.920053,3.010718,-1.171643
27,ENGI11,IBEP,2026-07-07,ENERGISA,UNT N2,3.255030e+08,0.744,0.012670,-0.243111,-0.106840,-15.941531,4.423431,0.767505,1.891727,0.751823
68,VIVT3,IBEP,2026-07-07,TELEF BRASIL,ON EJ,7.071257e+08,1.169,0.019331,0.010383,-0.008819,-15.998262,22.056719,0.530744,2.162234,1.364997
42,MOTV3,IBEP,2026-07-07,MOTIVA SA,ON NM,1.002197e+09,0.704,NaN,NaN,NaN,-16.456438,12.708265,1.118364,2.221615,-0.054812
55,SBSP3,IBEP,2026-07-07,SABESP,ON NM,3.506733e+09,4.991,0.108769,0.020655,-0.116366,-16.609860,43.474423,0.966865,4.831696,-0.269287
69,WEGE3,IBEP,2026-07-07,WEG,ON NM,1.485955e+09,3.293,0.032812,NaN,NaN,-16.818151,-7.706049,0.747138,9.075071,1.159148
34,IGTI11,IBEP,2026-07-07,IGUATEMI S.A,UNT N1,2.058010e+08,0.249,0.029292,-0.136129,-0.118724,-17.676100,1.077755,0.710089,-0.294677,2.962478
3,AURE3,IBEP,2026-07-07,AUREN,ON NM,3.177999e+08,0.186,0.003871,0.695373,-0.132830,-17.864474,11.485465,0.398011,-1.414734,4.528490
21,CURY3,IBEP,2026-07-07,CURY S/A,ON NM,1.609882e+08,0.261,0.104395,-1.919004,-0.334183,-18.378488,11.329173,0.736150,5.370642,2.415977
44,MULT3,IBEP,2026-07-07,MULTIPLAN,ON EJ N2,3.200222e+08,0.443,0.011417,-0.444003,-0.455867,-18.624641,10.899325,1.074966,2.557798,-1.946681
25,EMBJ3,IBEP,2026-07-07,EMBRAER,ON NM,7.118331e+08,2.942,-0.013919,-0.593536,-0.541634,-19.091945,52.923747,0.907242,-0.624506,5.170104
60,TIMS3,IBEP,2026-07-07,TIM,ON NM,7.774511e+08,0.838,-0.000309,-0.035122,-0.035122,-19.256010,23.749982,0.696296,3.785601,1.482676
23,DIRR3,IBEP,2026-07-07,DIRECIONAL,ON NM,3.270916e+08,0.217,0.151654,-0.050195,-0.012943,-19.703593,31.625806,1.074399,7.295263,0.905129
38,KLBN11,IBEP,2026-07-07,KLABIN S/A,UNT N2,8.045726e+08,0.655,-0.031637,-0.545447,-0.041675,-20.342498,-12.425795,0.447581,1.263106,3.697030
4,AXIA3,IBEP,2026-07-07,AXIA ENERGIA,ON NM,2.156760e+09,5.532,0.006771,0.000000,0.000000,-21.221146,11.219504,1.305664,9.067367,8.475443
47,PRIO3,IBEP,2026-07-07,PRIO,ON NM,7.572656e+08,1.943,0.030502,NaN,NaN,-23.980579,4.349439,1.138134,8.303391,4.729404
6,B3SA3,IBEP,2026-07-07,B3,ON NM,4.997060e+09,3.490,-0.001699,0.086040,0.087415,-25.465676,-0.999629,1.198894,3.795855,0.013255
46,POMO4,IBEP,2026-07-07,MARCOPOLO,PN N2,7.282662e+08,0.200,-0.031629,-0.540538,-0.443393,-28.146512,6.889492,0.914186,2.901652,6.557095
54,SANB11,IBEP,2026-07-07,SANTANDER BR,UNT,3.603472e+08,0.461,0.020907,0.437722,0.101965,-28.252636,-8.160040,1.066056,2.497079,3.468464
56,SLCE3,IBEP,2026-07-07,SLC AGRICOLA,ON NM,2.204037e+08,0.135,-0.051183,0.453835,-0.059302,-30.590062,-27.841004,0.476654,2.669749,1.444906
15,CMIN3,IBEP,2026-07-07,CSNMINERACAO,ON N2,1.646519e+09,0.341,0.030336,-0.242544,-0.218190,-31.784475,-14.872462,0.733417,0.344799,-1.105219
29,FLRY3,IBEP,2026-07-07,FLEURY,ON NM,4.471508e+08,0.335,0.019770,0.345059,0.101225,-32.010048,16.995584,0.776614,4.696631,3.295000
57,SMFT3,IBEP,2026-07-07,SMART FIT,ON NM,5.566513e+08,0.530,0.102864,0.238072,0.130604,-32.667158,-9.869008,0.831356,-1.728202,9.958413
1,ALOS3,IBEP,2026-07-07,ALLOS,ON NM,4.785587e+08,0.633,-0.010839,0.099930,-0.203833,-34.570038,26.759741,1.004755,4.101114,1.372963
67,VIVA3,IBEP,2026-07-07,VIVARA S.A.,ON NM,1.236983e+08,0.134,0.019249,NaN,NaN,-35.790227,-12.196668,1.407984,1.939578,7.233923
22,CYRE3,IBEP,2026-07-07,CYRELA REALT,ON ATZ NM,2.816093e+08,0.305,0.021727,0.074324,0.247089,-36.921422,-5.854538,1.408532,7.008300,2.120895
49,RADL3,IBEP,2026-07-07,RAIADROGASIL,ON EDJ NM,1.313916e+09,1.098,0.000799,-0.030909,-0.069610,-38.216706,-29.495766,0.624726,4.738652,2.123066
53,RENT3,IBEP,2026-07-07,LOCALIZA,ON EJ NM,9.784790e+08,1.890,-0.032858,-0.063132,0.029917,-38.380819,-27.699636,1.244739,4.888889,-0.219868
61,TOTS3,IBEP,2026-07-07,TOTVS,ON NM,5.339974e+08,0.729,0.369476,0.067323,0.077533,-39.296968,-27.214800,0.850178,3.438584,3.421850
58,SUZB3,IBEP,2026-07-07,SUZANO S.A.,ON NM,6.129185e+08,1.196,0.000043,-0.207931,-0.135792,-41.002750,-30.403401,0.281002,0.223214,3.213655
40,MBRF3,IBEP,2026-07-07,MARFRIG,ON NM,7.611753e+08,0.598,-0.008779,-0.141310,-0.018615,-42.332850,-5.515170,0.842912,0.518421,6.596806
51,RDOR3,IBEP,2026-07-07,REDE D OR,ON EJ NM,1.091469e+09,1.830,0.034045,-0.047052,-0.002775,-45.405886,41.628406,0.712768,2.671589,3.280894
50,RAIL3,IBEP,2026-07-07,RUMO S.A.,ON NM,1.221155e+09,0.790,0.014921,-0.462707,-0.182916,-46.134918,-33.670490,1.031126,5.611565,0.618539
14,CEAB3,IBEP,2026-07-07,CEA MODAS,ON NM,2.049643e+08,0.105,-0.073862,-0.379730,-0.360655,-47.709536,1.756485,1.605791,-2.883136,4.945586
33,HYPE3,IBEP,2026-07-07,HYPERA,ON EJ NM,3.210839e+08,0.318,0.040196,-0.071719,-0.092919,-52.558498,-27.936064,0.781145,2.860007,-2.007951
63,USIM5,IBEP,2026-07-07,USIMINAS,PNA N1,5.182568e+08,0.216,-0.025669,1.331015,-0.038451,-55.298864,2.095604,1.321616,9.607720,1.050667
2,ASAI3,IBEP,2026-07-07,ASSAI,ON NM,1.338623e+09,0.556,-0.013089,-0.025180,-0.103813,-58.676854,13.262795,0.692716,-2.619598,1.614223
52,RECV3,IBEP,2026-07-07,PETRORECSA,ON NM,2.746249e+08,0.125,0.043988,-0.036582,-0.039748,-60.241799,-24.124625,0.661492,1.264792,1.551726
12,BRAV3,IBEP,2026-07-07,BRAVA,ON NM,4.628830e+08,0.410,-0.000408,1.135116,0.287014,-63.121675,9.395908,0.688601,1.249569,0.652867
39,LREN3,IBEP,2026-07-07,LOJAS RENNER,ON NM,9.825937e+08,0.663,-0.035445,-0.329312,-0.334379,-65.348564,-9.575876,1.218046,0.488964,1.392870
43,MRVE3,IBEP,2026-07-07,MRV,ON NM,3.746814e+08,0.095,0.000370,0.024825,-0.075280,-74.660749,-37.217506,1.233511,5.562827,0.395675
9,BEEF3,IBEP,2026-07-07,MINERVA,ON NM,4.548049e+08,0.077,-0.052874,-0.082512,-0.085922,-76.079487,-49.986724,0.637097,1.702227,0.131277
5,AZZA3,IBEP,2026-07-07,AZZAS 2154,ON NM,1.095713e+08,0.092,0.018336,-0.274795,-0.314726,-79.624895,-63.948832,1.021580,2.120901,1.406373
65,VAMO3,IBEP,2026-07-07,VAMOS,ON NM,4.480521e+08,0.062,0.006114,-0.072400,0.082968,-81.493847,-12.996997,1.004723,8.306579,-2.612404
70,YDUQ3,IBEP,2026-07-07,YDUQS PART,ON NM,2.613658e+08,0.108,-0.065059,NaN,NaN,-82.281371,-33.075760,1.288097,4.432058,-5.061228
19,CSAN3,IBEP,2026-07-07,COSAN,ON NM,2.242672e+09,0.413,-0.240300,NaN,NaN,-84.584906,-72.163479,1.128848,4.830376,-1.659306
20,CSNA3,IBEP,2026-07-07,SID NACIONAL,ON,7.279750e+08,0.166,-0.034032,-0.756444,-0.045856,-86.201280,-64.657688,1.446341,7.435358,-5.094953
16,COGN3,IBEP,2026-07-07,COGNA ON,ON NM,1.915914e+09,0.207,-0.005607,NaN,NaN,-87.039487,-441.916141,1.351170,4.040917,-6.604560
45,NATU3,IBEP,2026-07-07,NATURA,ON NM,8.383595e+08,0.334,0.009475,NaN,NaN,-87.996500,-61.721526,0.708592,-10.681111,4.102207
13,BRKM5,IBEP,2026-07-07,BRASKEM,PNA ATZ N1,2.657097e+08,0.076,-0.093405,-0.001645,-0.065572,-89.982131,-64.026233,1.092134,-0.793701,0.949284
32,HAPV3,IBEP,2026-07-07,HAPVIDA,ON ATZ NM,2.716623e+08,0.135,0.004967,NaN,NaN,-96.250064,-68.957591,1.185217,2.054194,6.843017
41,MGLU3,IBEP,2026-07-07,MAGAZ LUIZA,ON NM,3.731551e+08,0.078,-0.018975,-0.028987,-0.146307,-98.112910,-87.634268,1.493129,5.346684,15.375054

In [2]:
df_final[df_final["Part. (%)"] > 5]

NameError: name 'df_final' is not defined